#define MAXSTEP 8
#include "../logic/one-type-sensitive-pt.dl"

.init typeDemo1 = OneTypeSensitivePT
typeDemo1.Reachable("<com.bytecodedl.benchmark.demo.ContextSensitiveDemo1: void main(java.lang.String[])>", "initCtx", 0).
.output typeDemo1.VarPointsTo

.init typeDemo2 = OneTypeSensitivePT
typeDemo2.Reachable("<com.bytecodedl.benchmark.demo.ContextSensitiveDemo2: void main(java.lang.String[])>", "initCtx", 0).
.output typeDemo2.VarPointsTo