version: '2.4'
services:
  bytecodedl:
    image: wuxxxxx/bytecodedl:1.0.0
    restart: always
    command: sleep infinity
    volumes:
        - ./:/bytecodedl
  neo:
    image: wuxxxxx/neo4j-server:5.12.0-bytecodedl-pathfinder-1.0.0 
    restart: always
    ports:
      - "0.0.0.0:7474:7474"
      - "0.0.0.0:7687:7687"
    volumes:
        - ./:/bytecodedl
